In [1]:
import pandas as pd

In [2]:
df_2022 = pd.read_parquet("enem_parquet/2022")

In [3]:
df_2022

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210057943671,2022,14,M,2,2,1,1,2,1,...,B,A,A,A,A,A,A,A,A,A
1,210057516120,2022,14,M,2,1,1,1,16,1,...,E,E,B,E,B,B,E,B,E,B
2,210057280536,2022,5,F,1,2,1,1,2,1,...,A,A,A,A,A,A,C,A,A,B
3,210055724397,2022,6,M,1,3,1,1,2,1,...,B,A,A,C,A,A,C,B,B,B
4,210055097896,2022,4,M,0,3,1,1,1,1,...,A,A,A,A,A,A,B,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3476100,210056490014,2022,3,F,1,3,1,1,1,1,...,A,A,A,B,B,A,B,A,A,B
3476101,210057345158,2022,3,M,1,1,1,2,0,2,...,B,A,A,B,A,A,E,A,B,B
3476102,210056006438,2022,2,F,1,1,1,3,0,1,...,B,A,B,D,A,B,E,A,B,B
3476103,210057209705,2022,4,F,1,1,1,1,2,1,...,B,A,A,B,A,A,C,A,B,B
3476104,210057031929,2022,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,C,A,A,B

In [4]:
colunas_nao_usadas = [
    'NU_INSCRICAO', 'NU_ANO', 'TP_SEXO', 'TP_ESTADO_CIVIL', 
    'TP_NACIONALIDADE', 'TP_ANO_CONCLUIU', 'CO_MUNICIPIO_ESC', 
    'NO_MUNICIPIO_ESC', 'SG_UF_ESC', 'CO_MUNICIPIO_PROVA', 
    'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 
    
    'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 
    'CO_PROVA_MT', 'TP_LINGUA',
    
    'Q005', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 
    'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 
    'Q020', 'Q021', 'Q023'
]

df_2022.drop(columns=colunas_nao_usadas, inplace=True, errors='ignore')

In [5]:
df_2022.isna().sum()

TP_FAIXA_ETARIA                 0
TP_COR_RACA                     0
TP_ST_CONCLUSAO                 0
TP_ESCOLA                       0
TP_ENSINO                 2213361
IN_TREINEIRO                    0
CO_UF_ESC                 2524161
TP_DEPENDENCIA_ADM_ESC    2524161
TP_LOCALIZACAO_ESC        2524161
TP_SIT_FUNC_ESC           2524161
TP_PRESENCA_CN                  0
TP_PRESENCA_CH                  0
TP_PRESENCA_LC                  0
TP_PRESENCA_MT                  0
NU_NOTA_CN                1120710
NU_NOTA_CH                 982663
NU_NOTA_LC                 982663
NU_NOTA_MT                1120710
TX_RESPOSTAS_CN           1120710
TX_RESPOSTAS_CH            982663
TX_RESPOSTAS_LC            982663
TX_RESPOSTAS_MT           1120710
TX_GABARITO_CN            1120710
TX_GABARITO_CH             982663
TX_GABARITO_LC             982663
TX_GABARITO_MT            1120710
TP_STATUS_REDACAO          982663
NU_NOTA_COMP1              982663
NU_NOTA_COMP2              982663
NU_NOTA_COMP3              982663
NU_NOTA_COMP4              982663
NU_NOTA_COMP5              982663
NU_NOTA_REDACAO            982663
Q001                            0
Q002                            0
Q003                            0
Q004                            0
Q006                            0
Q022                            0
Q024                            0
Q025                            0
dtype: int64

In [6]:
df_2022 = df_2022.dropna()

In [7]:
df_2022.isna().sum()

TP_FAIXA_ETARIA           0
TP_COR_RACA               0
TP_ST_CONCLUSAO           0
TP_ESCOLA                 0
TP_ENSINO                 0
IN_TREINEIRO              0
CO_UF_ESC                 0
TP_DEPENDENCIA_ADM_ESC    0
TP_LOCALIZACAO_ESC        0
TP_SIT_FUNC_ESC           0
TP_PRESENCA_CN            0
TP_PRESENCA_CH            0
TP_PRESENCA_LC            0
TP_PRESENCA_MT            0
NU_NOTA_CN                0
NU_NOTA_CH                0
NU_NOTA_LC                0
NU_NOTA_MT                0
TX_RESPOSTAS_CN           0
TX_RESPOSTAS_CH           0
TX_RESPOSTAS_LC           0
TX_RESPOSTAS_MT           0
TX_GABARITO_CN            0
TX_GABARITO_CH            0
TX_GABARITO_LC            0
TX_GABARITO_MT            0
TP_STATUS_REDACAO         0
NU_NOTA_COMP1             0
NU_NOTA_COMP2             0
NU_NOTA_COMP3             0
NU_NOTA_COMP4             0
NU_NOTA_COMP5             0
NU_NOTA_REDACAO           0
Q001                      0
Q002                      0
Q003                      0
Q004                      0
Q006                      0
Q022                      0
Q024                      0
Q025                      0
dtype: int64

In [8]:
df_2022

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
40,5,3,2,2,1,0,23,2,1,1,...,100,560,C,D,C,B,B,C,A,B
55,3,1,2,2,1,0,35,4,1,1,...,200,900,D,F,B,D,E,E,B,B
57,2,3,2,2,1,0,52,2,1,1,...,160,740,C,D,F,C,F,E,C,B
59,3,3,2,2,2,0,15,2,1,1,...,20,520,E,E,C,F,B,A,A,B
67,3,1,2,2,1,0,33,2,1,1,...,80,540,D,E,B,B,D,D,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3476077,2,3,2,2,1,0,31,4,1,1,...,200,820,F,F,D,D,H,E,D,B
3476090,3,1,2,3,1,0,21,4,1,1,...,160,820,G,F,E,D,O,D,B,B
3476094,3,3,2,2,1,0,23,2,1,1,...,100,580,B,C,A,A,A,E,A,B
3476095,2,1,2,2,1,0,27,2,1,1,...,160,800,C,B,C,B,B,D,A,B
3476098,3,1,2,2,1,0,17,2,1,1,...,0,0,D,D,F,F,D,B,C,B

In [9]:
df_2022['TP_STATUS_REDACAO'].value_counts()

TP_STATUS_REDACAO
1    649703
4     12768
3      8689
6      7423
8      2425
2       384
9       355
7       153
Name: count, dtype: Int64

In [10]:
df_2022 = df_2022[df_2022['TP_STATUS_REDACAO'] == 1]

In [11]:
df_2022

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
40,5,3,2,2,1,0,23,2,1,1,...,100,560,C,D,C,B,B,C,A,B
55,3,1,2,2,1,0,35,4,1,1,...,200,900,D,F,B,D,E,E,B,B
57,2,3,2,2,1,0,52,2,1,1,...,160,740,C,D,F,C,F,E,C,B
59,3,3,2,2,2,0,15,2,1,1,...,20,520,E,E,C,F,B,A,A,B
67,3,1,2,2,1,0,33,2,1,1,...,80,540,D,E,B,B,D,D,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3476074,3,4,2,2,1,0,28,2,1,1,...,80,700,E,E,B,B,D,E,B,B
3476077,2,3,2,2,1,0,31,4,1,1,...,200,820,F,F,D,D,H,E,D,B
3476090,3,1,2,3,1,0,21,4,1,1,...,160,820,G,F,E,D,O,D,B,B
3476094,3,3,2,2,1,0,23,2,1,1,...,100,580,B,C,A,A,A,E,A,B
3476095,2,1,2,2,1,0,27,2,1,1,...,160,800,C,B,C,B,B,D,A,B

In [12]:
df_2022['IN_TREINEIRO'].value_counts()

IN_TREINEIRO
0    649703
Name: count, dtype: Int64

In [13]:
df_2022['TP_PRESENCA_CN'].value_counts()

TP_PRESENCA_CN
1    649703
Name: count, dtype: Int64

In [14]:
df_2022['TP_PRESENCA_CH'].value_counts()

TP_PRESENCA_CH
1    649703
Name: count, dtype: Int64

In [15]:
df_2022['TP_ST_CONCLUSAO'].value_counts()

TP_ST_CONCLUSAO
2    649703
Name: count, dtype: Int64

In [16]:
df_2022.to_parquet("dados2022_limpos")