In [1]:
import pandas as pd

In [2]:
df_2020 = pd.read_parquet("enem_parquet/2020")

In [3]:
df_2020

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,200006271946,2020,11,F,1,2,1,1,11,1,...,None,None,None,None,None,None,None,None,None,None
1,200001195856,2020,11,M,2,3,1,1,11,1,...,None,None,None,None,None,None,None,None,None,None
2,200001943954,2020,4,F,2,3,2,2,0,2,...,B,A,A,B,A,A,A,A,A,A
3,200001908998,2020,2,M,1,3,1,2,0,2,...,None,None,None,None,None,None,None,None,None,None
4,200001634757,2020,4,F,1,3,2,1,1,1,...,A,A,A,B,A,B,B,A,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5783104,200004393462,2020,2,F,1,1,1,3,0,1,...,B,B,B,C,B,B,E,B,C,B
5783105,200003075563,2020,6,M,1,3,1,1,3,1,...,B,A,B,B,B,A,D,B,B,B
5783106,200005896891,2020,2,M,1,1,1,2,0,3,...,B,A,A,C,A,B,D,B,B,B
5783107,200001728973,2020,8,M,1,3,1,1,4,1,...,A,A,A,B,A,A,C,A,A,A
5783108,200005120080,2020,3,F,1,1,1,2,0,2,...,B,A,A,C,B,A,C,A,B,B

In [4]:
colunas_nao_usadas = [
    'NU_INSCRICAO', 'NU_ANO', 'TP_SEXO', 'TP_ESTADO_CIVIL', 
    'TP_NACIONALIDADE', 'TP_ANO_CONCLUIU', 'CO_MUNICIPIO_ESC', 
    'NO_MUNICIPIO_ESC', 'SG_UF_ESC', 'CO_MUNICIPIO_PROVA', 
    'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 
    
    'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 
    'CO_PROVA_MT', 'TP_LINGUA',
    
    'Q005', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 
    'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 
    'Q020', 'Q021', 'Q023'
]

df_2020.drop(columns=colunas_nao_usadas, inplace=True, errors='ignore')

In [5]:
df_2020.isna().sum()

TP_FAIXA_ETARIA                 0
TP_COR_RACA                     0
TP_ST_CONCLUSAO                 0
TP_ESCOLA                       0
TP_ENSINO                 4479663
IN_TREINEIRO                    0
CO_UF_ESC                 4878540
TP_DEPENDENCIA_ADM_ESC    4878540
TP_LOCALIZACAO_ESC        4878540
TP_SIT_FUNC_ESC           4878540
TP_PRESENCA_CN                  0
TP_PRESENCA_CH                  0
TP_PRESENCA_LC                  0
TP_PRESENCA_MT                  0
NU_NOTA_CN                3185669
NU_NOTA_CH                3028969
NU_NOTA_LC                3028969
NU_NOTA_MT                3185669
TX_RESPOSTAS_CN           3185669
TX_RESPOSTAS_CH           3028969
TX_RESPOSTAS_LC           3028969
TX_RESPOSTAS_MT           3185669
TX_GABARITO_CN            3185669
TX_GABARITO_CH            3028969
TX_GABARITO_LC            3028969
TX_GABARITO_MT            3185669
TP_STATUS_REDACAO         3028969
NU_NOTA_COMP1             3028969
NU_NOTA_COMP2             3028969
NU_NOTA_COMP3             3028969
NU_NOTA_COMP4             3028969
NU_NOTA_COMP5             3028969
NU_NOTA_REDACAO           3028969
Q001                        95966
Q002                        95966
Q003                        95966
Q004                        95966
Q006                        95966
Q022                        95966
Q024                        95966
Q025                        95966
dtype: int64

In [6]:
df_2020 = df_2020.dropna()

In [7]:
df_2020.isna().sum()

TP_FAIXA_ETARIA           0
TP_COR_RACA               0
TP_ST_CONCLUSAO           0
TP_ESCOLA                 0
TP_ENSINO                 0
IN_TREINEIRO              0
CO_UF_ESC                 0
TP_DEPENDENCIA_ADM_ESC    0
TP_LOCALIZACAO_ESC        0
TP_SIT_FUNC_ESC           0
TP_PRESENCA_CN            0
TP_PRESENCA_CH            0
TP_PRESENCA_LC            0
TP_PRESENCA_MT            0
NU_NOTA_CN                0
NU_NOTA_CH                0
NU_NOTA_LC                0
NU_NOTA_MT                0
TX_RESPOSTAS_CN           0
TX_RESPOSTAS_CH           0
TX_RESPOSTAS_LC           0
TX_RESPOSTAS_MT           0
TX_GABARITO_CN            0
TX_GABARITO_CH            0
TX_GABARITO_LC            0
TX_GABARITO_MT            0
TP_STATUS_REDACAO         0
NU_NOTA_COMP1             0
NU_NOTA_COMP2             0
NU_NOTA_COMP3             0
NU_NOTA_COMP4             0
NU_NOTA_COMP5             0
NU_NOTA_REDACAO           0
Q001                      0
Q002                      0
Q003                      0
Q004                      0
Q006                      0
Q022                      0
Q024                      0
Q025                      0
dtype: int64

In [8]:
df_2020

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
36,3,3,2,2,1,0,13,2,1,1,...,120,620,E,E,A,A,B,D,A,A
65,3,3,2,2,1,0,22,1,1,1,...,200,880,A,C,A,A,B,C,A,A
84,2,3,2,2,1,0,51,2,1,1,...,120,600,C,E,C,B,B,E,A,A
89,2,1,2,2,1,0,35,2,1,1,...,180,820,B,C,C,A,C,C,B,B
93,4,2,2,2,1,0,33,1,1,1,...,200,920,E,E,C,C,F,D,C,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5783089,2,1,2,3,1,0,23,4,1,1,...,120,780,E,E,D,B,J,E,B,B
5783093,3,3,2,2,1,0,23,2,1,1,...,160,780,B,C,A,B,B,C,A,A
5783096,3,0,2,2,1,0,31,4,1,1,...,180,940,G,F,E,D,N,D,C,B
5783101,2,1,2,2,1,0,43,2,1,1,...,160,780,D,G,C,D,E,C,C,B
5783106,2,1,2,3,1,0,33,4,1,1,...,200,940,E,G,D,E,O,D,B,B

In [9]:
df_2020['TP_STATUS_REDACAO'].value_counts()

TP_STATUS_REDACAO
1    509871
4      4104
6      2749
3      2199
8       760
9       417
2       387
7       250
Name: count, dtype: Int64

In [10]:
df_2020 = df_2020[df_2020['TP_STATUS_REDACAO'] == 1]

In [11]:
df_2020

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
36,3,3,2,2,1,0,13,2,1,1,...,120,620,E,E,A,A,B,D,A,A
65,3,3,2,2,1,0,22,1,1,1,...,200,880,A,C,A,A,B,C,A,A
84,2,3,2,2,1,0,51,2,1,1,...,120,600,C,E,C,B,B,E,A,A
89,2,1,2,2,1,0,35,2,1,1,...,180,820,B,C,C,A,C,C,B,B
93,4,2,2,2,1,0,33,1,1,1,...,200,920,E,E,C,C,F,D,C,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5783089,2,1,2,3,1,0,23,4,1,1,...,120,780,E,E,D,B,J,E,B,B
5783093,3,3,2,2,1,0,23,2,1,1,...,160,780,B,C,A,B,B,C,A,A
5783096,3,0,2,2,1,0,31,4,1,1,...,180,940,G,F,E,D,N,D,C,B
5783101,2,1,2,2,1,0,43,2,1,1,...,160,780,D,G,C,D,E,C,C,B
5783106,2,1,2,3,1,0,33,4,1,1,...,200,940,E,G,D,E,O,D,B,B

In [12]:
df_2020['IN_TREINEIRO'].value_counts()

IN_TREINEIRO
0    509871
Name: count, dtype: Int64

In [13]:
df_2020['TP_PRESENCA_CN'].value_counts()

TP_PRESENCA_CN
1    509871
Name: count, dtype: Int64

In [14]:
df_2020['TP_PRESENCA_CH'].value_counts()

TP_PRESENCA_CH
1    509871
Name: count, dtype: Int64

In [15]:
df_2020['TP_ST_CONCLUSAO'].value_counts()

TP_ST_CONCLUSAO
2    509871
Name: count, dtype: Int64

In [16]:
df_2020.to_parquet("dados2020_limpos")