In [1]:
import pandas as pd

In [2]:
df_2019 = pd.read_parquet("enem_parquet/2019/")
df_2019_descricao = pd.read_csv("descricao.csv")

In [3]:
df_2019

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001595656,2019,13,M,1,3,1,1,11,1,...,A,A,A,A,A,A,C,A,C,B
1,190001421546,2019,8,M,1,1,1,1,5,1,...,A,A,A,B,A,A,E,A,A,B
2,190001133210,2019,13,F,1,3,1,1,13,1,...,A,A,A,B,A,A,C,A,A,B
3,190001199383,2019,10,F,1,1,1,1,4,1,...,A,A,A,C,A,B,D,A,B,B
4,190001237802,2019,7,F,1,1,1,1,4,1,...,B,A,A,B,A,A,C,B,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095166,190003061751,2019,4,F,1,3,1,4,0,1,...,A,A,A,B,B,B,D,A,A,B
5095167,190003286152,2019,3,F,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,A,B
5095168,190003071099,2019,14,F,2,1,1,1,13,1,...,A,A,A,B,A,A,C,A,A,A
5095169,190003382827,2019,5,M,1,1,1,1,2,1,...,A,A,A,B,A,A,D,B,C,B
5095170,190002775679,2019,5,F,1,3,1,1,2,1,...,A,A,A,B,B,A,C,A,A,B

In [4]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(df_2019_descricao)

,Coluna,Descrição
0,NU_INSCRICAO,Número de inscrição
1,NU_ANO,Ano do Enem
2,TP_FAIXA_ETARIA,Faixa etária
3,TP_SEXO,Sexo
4,TP_ESTADO_CIVIL,Estado Civil
5,TP_COR_RACA,Cor/raça
6,TP_NACIONALIDADE,Nacionalidade
7,TP_ST_CONCLUSAO,Situação de conclusão do Ensino Médio
8,TP_ANO_CONCLUIU,Ano de Conclusão do Ensino Médio
9,TP_ESCOLA,Tipo de escola do Ensino Médio
10,TP_ENSINO,Tipo de instituição que concluiu ou concluirá o Ensino Médio
11,IN_TREINEIRO,Indica se o inscrito é treineiro
12,CO_MUNICIPIO_ESC,Código do município da escola
13,NO_MUNICIPIO_ESC,Nome do município da escola
14,CO_UF_ESC,Código da Unidade da Federação da escola
15,SG_UF_ESC,Sigla da Unidade da Federação da escola
16,TP_DEPENDENCIA_ADM_ESC,"Dependência administrativa da escola (Federal, Estadual, etc.)"
17,TP_LOCALIZACAO_ESC,Localização da escola (Urbana/Rural)
18,TP_SIT_FUNC_ESC,Situação de funcionamento da escola
19,CO_MUNICIPIO_PROVA,Código do município de aplicação da prova
20,NO_MUNICIPIO_PROVA,Nome do município de aplicação da prova
21,CO_UF_PROVA,Código da Unidade da Federação de aplicação da prova
22,SG_UF_PROVA,Sigla da Unidade da Federação de aplicação da prova
23,TP_PRESENCA_CN,Presença na prova objetiva de Ciências da Natureza
24,TP_PRESENCA_CH,Presença na prova objetiva de Ciências Humanas
25,TP_PRESENCA_LC,Presença na prova objetiva de Linguagens e Códigos
26,TP_PRESENCA_MT,Presença na prova objetiva de Matemática
27,CO_PROVA_CN,Código do tipo de prova de Ciências da Natureza
28,CO_PROVA_CH,Código do tipo de prova de Ciências Humanas
29,CO_PROVA_LC,Código do tipo de prova de Linguagens e Códigos
30,CO_PROVA_MT,Código do tipo de prova de Matemática
31,NU_NOTA_CN,Nota da prova de Ciências da Natureza
32,NU_NOTA_CH,Nota da prova de Ciências Humanas
33,NU_NOTA_LC,Nota da prova de Linguagens e Códigos
34,NU_NOTA_MT,Nota da prova de Matemática
35,TX_RESPOSTAS_CN,Vetor com as respostas da prova de Ciências da Natureza
36,TX_RESPOSTAS_CH,Vetor com as respostas da prova de Ciências Humanas
37,TX_RESPOSTAS_LC,Vetor com as respostas da prova de Linguagens e Códigos
38,TX_RESPOSTAS_MT,Vetor com as respostas da prova de Matemática
39,TP_LINGUA,"Língua Estrangeira (0 - Inglês, 1 - Espanhol)"
40,TX_GABARITO_CN,Vetor com o gabarito da prova de Ciências da Natureza
41,TX_GABARITO_CH,Vetor com o gabarito da prova de Ciências Humanas
42,TX_GABARITO_LC,Vetor com o gabarito da prova de Linguagens e Códigos
43,TX_GABARITO_MT,Vetor com o gabarito da prova de Matemática
44,TP_STATUS_REDACAO,Situação da redação
45,NU_NOTA_COMP1,Nota da competência 1 da redação
46,NU_NOTA_COMP2,Nota da competência 2 da redação
47,NU_NOTA_COMP3,Nota da competência 3 da redação
48,NU_NOTA_COMP4,Nota da competência 4 da redação
49,NU_NOTA_COMP5,Nota da competência 5 da redação
50,NU_NOTA_REDACAO,Nota total da redação
51,Q001,"Até que série seu pai, ou o homem responsável por você, estudou?"
52,Q002,"Até que série sua mãe, ou a mulher responsável por você, estudou?"
53,Q003,Grupo de ocupação do seu pai ou responsável
54,Q004,Grupo de ocupação da sua mãe ou responsável
55,Q005,Quantas pessoas moram na sua residência?
56,Q006,Qual é a renda mensal de sua família? (Soma de todos)
57,Q007,Em sua residência trabalha empregado(a) doméstico(a)?
58,Q008,Na sua residência tem banheiro?
59,Q009,Na sua residência tem quartos para dormir?
60,Q010,Na sua residência tem carro?
61,Q011,Na sua residência tem motocicleta?
62,Q012,Na sua residência tem geladeira?
63,Q013,Na sua residência tem freezer?
64,Q014,Na sua residência tem máquina de lavar roupa?
65,Q015,Na sua residência tem máquina de secar roupa?
66,Q016,Na sua residência tem forno micro-ondas?
67,Q017,Na sua residência tem máquina de lavar louça?
68,Q018,Na sua residência tem aspirador de pó?
69,Q019,Na sua residência tem televisão em cores?
70,Q020,Na sua residência tem aparelho de DVD?
71,Q021,Na sua residência tem TV por assinatura?
72,Q022,Na sua residência tem telefone celular?
73,Q023,Na sua residência tem telefone fixo?
74,Q024,Na sua residência tem computador?
75,Q025,Na sua residência tem acesso à Internet?

In [5]:
colunas_nao_usadas = [
    'NU_INSCRICAO', 'NU_ANO', 'TP_SEXO', 'TP_ESTADO_CIVIL', 
    'TP_NACIONALIDADE', 'TP_ANO_CONCLUIU', 'CO_MUNICIPIO_ESC', 
    'NO_MUNICIPIO_ESC', 'SG_UF_ESC', 'CO_MUNICIPIO_PROVA', 
    'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 
    
    'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 
    'CO_PROVA_MT', 'TP_LINGUA',
    
    'Q005', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 
    'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 
    'Q020', 'Q021', 'Q023'
]

df_2019.drop(columns=colunas_nao_usadas, inplace=True, errors='ignore')

In [6]:
df_2019

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
0,13,3,1,1,<NA>,0,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,B,B,A,A,A,C,C,B
1,8,1,1,1,1,0,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,C,E,B,B,C,E,A,B
2,13,3,1,1,1,0,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,E,E,B,C,B,C,A,B
3,10,1,1,1,<NA>,0,<NA>,<NA>,<NA>,<NA>,...,0,460,C,E,B,D,E,D,B,B
4,7,1,1,1,1,0,<NA>,<NA>,<NA>,<NA>,...,200,860,E,E,C,C,G,C,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095166,4,3,4,1,<NA>,0,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,D,B,D,A,B,D,A,B
5095167,3,3,2,2,1,0,23,2,1,1,...,<NA>,<NA>,H,H,F,F,B,B,A,B
5095168,14,1,1,1,1,0,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,H,E,B,D,E,C,A,A
5095169,5,1,1,1,<NA>,0,<NA>,<NA>,<NA>,<NA>,...,180,880,E,G,C,D,J,D,C,B
5095170,5,3,1,1,1,0,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,A,A,A,A,B,C,A,B

In [7]:
df_2019.isna().sum()

TP_FAIXA_ETARIA                 0
TP_COR_RACA                     0
TP_ST_CONCLUSAO                 0
TP_ESCOLA                       0
TP_ENSINO                 2217036
IN_TREINEIRO                    0
CO_UF_ESC                 3947784
TP_DEPENDENCIA_ADM_ESC    3947784
TP_LOCALIZACAO_ESC        3947784
TP_SIT_FUNC_ESC           3947784
TP_PRESENCA_CN                  0
TP_PRESENCA_CH                  0
TP_PRESENCA_LC                  0
TP_PRESENCA_MT                  0
NU_NOTA_CN                1384836
NU_NOTA_CH                1172125
NU_NOTA_LC                1172125
NU_NOTA_MT                1384836
TX_RESPOSTAS_CN           1384836
TX_RESPOSTAS_CH           1172125
TX_RESPOSTAS_LC           1172125
TX_RESPOSTAS_MT           1384836
TX_GABARITO_CN            1384836
TX_GABARITO_CH            1172125
TX_GABARITO_LC            1172125
TX_GABARITO_MT            1384836
TP_STATUS_REDACAO         1172126
NU_NOTA_COMP1             1172126
NU_NOTA_COMP2             1172126
NU_NOTA_COMP3             1172126
NU_NOTA_COMP4             1172126
NU_NOTA_COMP5             1172126
NU_NOTA_REDACAO           1172126
Q001                            0
Q002                            0
Q003                            0
Q004                            0
Q006                            0
Q022                            0
Q024                            0
Q025                            0
dtype: int64

In [8]:
df_2019 = df_2019.dropna()

In [9]:
df_2019.isna().sum()

TP_FAIXA_ETARIA           0
TP_COR_RACA               0
TP_ST_CONCLUSAO           0
TP_ESCOLA                 0
TP_ENSINO                 0
IN_TREINEIRO              0
CO_UF_ESC                 0
TP_DEPENDENCIA_ADM_ESC    0
TP_LOCALIZACAO_ESC        0
TP_SIT_FUNC_ESC           0
TP_PRESENCA_CN            0
TP_PRESENCA_CH            0
TP_PRESENCA_LC            0
TP_PRESENCA_MT            0
NU_NOTA_CN                0
NU_NOTA_CH                0
NU_NOTA_LC                0
NU_NOTA_MT                0
TX_RESPOSTAS_CN           0
TX_RESPOSTAS_CH           0
TX_RESPOSTAS_LC           0
TX_RESPOSTAS_MT           0
TX_GABARITO_CN            0
TX_GABARITO_CH            0
TX_GABARITO_LC            0
TX_GABARITO_MT            0
TP_STATUS_REDACAO         0
NU_NOTA_COMP1             0
NU_NOTA_COMP2             0
NU_NOTA_COMP3             0
NU_NOTA_COMP4             0
NU_NOTA_COMP5             0
NU_NOTA_REDACAO           0
Q001                      0
Q002                      0
Q003                      0
Q004                      0
Q006                      0
Q022                      0
Q024                      0
Q025                      0
dtype: int64

In [10]:
df_2019

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
26,2,1,2,3,1,0,41,4,1,1,...,160,900,E,E,B,B,E,C,B,B
28,3,1,2,2,1,0,43,2,1,1,...,40,580,E,B,B,B,A,D,B,A
31,2,2,2,2,1,0,35,2,1,1,...,140,660,E,F,B,D,B,D,A,B
34,2,2,2,2,1,0,29,2,1,1,...,100,620,E,C,B,B,B,C,A,B
53,3,3,2,2,1,0,25,2,1,1,...,0,480,D,E,C,B,C,E,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095143,2,3,2,2,1,0,26,1,1,1,...,80,480,E,E,F,D,E,C,B,B
5095151,3,4,2,2,1,0,26,2,1,1,...,0,440,E,E,A,A,B,A,A,A
5095152,2,3,2,2,1,0,35,2,1,1,...,40,520,E,E,F,F,B,B,B,B
5095158,3,3,2,2,1,0,23,2,1,1,...,40,520,D,C,C,A,B,E,B,B
5095162,2,1,2,3,1,0,26,4,1,1,...,140,620,F,F,E,E,Q,D,D,B

In [11]:
df_2019['TP_STATUS_REDACAO'].value_counts()

TP_STATUS_REDACAO
1    880332
4     11087
6      7408
3      6641
8      1918
2       677
9       604
7       503
Name: count, dtype: Int64

In [12]:
df_2019 = df_2019[df_2019['TP_STATUS_REDACAO'] == 1]

In [13]:
df_2019

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
26,2,1,2,3,1,0,41,4,1,1,...,160,900,E,E,B,B,E,C,B,B
28,3,1,2,2,1,0,43,2,1,1,...,40,580,E,B,B,B,A,D,B,A
31,2,2,2,2,1,0,35,2,1,1,...,140,660,E,F,B,D,B,D,A,B
34,2,2,2,2,1,0,29,2,1,1,...,100,620,E,C,B,B,B,C,A,B
53,3,3,2,2,1,0,25,2,1,1,...,0,480,D,E,C,B,C,E,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095143,2,3,2,2,1,0,26,1,1,1,...,80,480,E,E,F,D,E,C,B,B
5095151,3,4,2,2,1,0,26,2,1,1,...,0,440,E,E,A,A,B,A,A,A
5095152,2,3,2,2,1,0,35,2,1,1,...,40,520,E,E,F,F,B,B,B,B
5095158,3,3,2,2,1,0,23,2,1,1,...,40,520,D,C,C,A,B,E,B,B
5095162,2,1,2,3,1,0,26,4,1,1,...,140,620,F,F,E,E,Q,D,D,B

In [14]:
df_2019['IN_TREINEIRO'].value_counts()

IN_TREINEIRO
0    880332
Name: count, dtype: Int64

In [15]:
df_2019['TP_ESCOLA'].value_counts()

TP_ESCOLA
2    756702
3    123630
Name: count, dtype: Int64

In [16]:
df_2019['TP_ENSINO'].value_counts()

TP_ENSINO
1    878109
2      2223
Name: count, dtype: Int64

In [17]:
df_2019['TP_PRESENCA_CN'].value_counts()

TP_PRESENCA_CN
1    880332
Name: count, dtype: Int64

In [18]:
df_2019['TP_PRESENCA_CH'].value_counts()

TP_PRESENCA_CH
1    880332
Name: count, dtype: Int64

In [19]:
df_2019['TP_ST_CONCLUSAO'].value_counts()

TP_ST_CONCLUSAO
2    880332
Name: count, dtype: Int64

lembrete: se nos outros datasets uma coluna tiver apenas 1 valor como é o caso de algumas aqui, retire!

In [20]:
df_2019.to_parquet("dados2019_limpos")