In [1]:
import pandas as pd

In [2]:
df_2021 = pd.read_parquet("enem_parquet/2021")

In [3]:
df_2021

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210053865474,2021,5,F,1,1,1,1,3,1,...,A,A,A,B,A,A,B,A,B,B
1,210052384164,2021,12,M,1,1,1,1,11,1,...,A,A,A,B,A,A,C,A,A,A
2,210052589243,2021,13,F,3,1,1,1,15,1,...,B,A,A,B,A,A,C,B,B,B
3,210052128335,2021,3,M,1,3,1,2,0,2,...,A,A,A,B,A,A,B,A,B,B
4,210051353021,2021,2,F,1,3,1,2,0,2,...,B,A,A,B,A,B,E,A,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389827,210052571466,2021,9,M,1,3,1,1,7,1,...,A,A,A,B,B,A,C,A,B,B
3389828,210052207206,2021,3,F,2,1,1,2,0,2,...,B,A,A,A,A,A,C,A,C,B
3389829,210051224444,2021,2,M,1,1,1,3,0,1,...,A,A,A,B,A,A,B,A,A,B
3389830,210052150977,2021,5,F,1,3,1,1,3,1,...,A,A,A,B,A,A,E,A,B,B
3389831,210051984641,2021,5,F,1,3,1,2,0,2,...,B,A,A,B,A,A,C,A,A,B

In [4]:
colunas_nao_usadas = [
    'NU_INSCRICAO', 'NU_ANO', 'TP_SEXO', 'TP_ESTADO_CIVIL', 
    'TP_NACIONALIDADE', 'TP_ANO_CONCLUIU', 'CO_MUNICIPIO_ESC', 
    'NO_MUNICIPIO_ESC', 'SG_UF_ESC', 'CO_MUNICIPIO_PROVA', 
    'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 
    
    'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC', 
    'CO_PROVA_MT', 'TP_LINGUA',
    
    'Q005', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 
    'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 
    'Q020', 'Q021', 'Q023'
]

df_2021.drop(columns=colunas_nao_usadas, inplace=True, errors='ignore')

In [5]:
df_2021.isna().sum()

TP_FAIXA_ETARIA                 0
TP_COR_RACA                     0
TP_ST_CONCLUSAO                 0
TP_ESCOLA                       0
TP_ENSINO                 2293004
IN_TREINEIRO                    0
CO_UF_ESC                 2576026
TP_DEPENDENCIA_ADM_ESC    2576026
TP_LOCALIZACAO_ESC        2576026
TP_SIT_FUNC_ESC           2576026
TP_PRESENCA_CN                  0
TP_PRESENCA_CH                  0
TP_PRESENCA_LC                  0
TP_PRESENCA_MT                  0
NU_NOTA_CN                1143988
NU_NOTA_CH                1011453
NU_NOTA_LC                1011453
NU_NOTA_MT                1143988
TX_RESPOSTAS_CN           1143988
TX_RESPOSTAS_CH           1011453
TX_RESPOSTAS_LC           1011453
TX_RESPOSTAS_MT           1143988
TX_GABARITO_CN            1143988
TX_GABARITO_CH            1011453
TX_GABARITO_LC            1011453
TX_GABARITO_MT            1143988
TP_STATUS_REDACAO         1011453
NU_NOTA_COMP1             1011453
NU_NOTA_COMP2             1011453
NU_NOTA_COMP3             1011453
NU_NOTA_COMP4             1011453
NU_NOTA_COMP5             1011453
NU_NOTA_REDACAO           1011453
Q001                            2
Q002                            2
Q003                            2
Q004                            2
Q006                            2
Q022                            2
Q024                            2
Q025                            2
dtype: int64

In [6]:
df_2021 = df_2021.dropna()

In [7]:
df_2021.isna().sum()

TP_FAIXA_ETARIA           0
TP_COR_RACA               0
TP_ST_CONCLUSAO           0
TP_ESCOLA                 0
TP_ENSINO                 0
IN_TREINEIRO              0
CO_UF_ESC                 0
TP_DEPENDENCIA_ADM_ESC    0
TP_LOCALIZACAO_ESC        0
TP_SIT_FUNC_ESC           0
TP_PRESENCA_CN            0
TP_PRESENCA_CH            0
TP_PRESENCA_LC            0
TP_PRESENCA_MT            0
NU_NOTA_CN                0
NU_NOTA_CH                0
NU_NOTA_LC                0
NU_NOTA_MT                0
TX_RESPOSTAS_CN           0
TX_RESPOSTAS_CH           0
TX_RESPOSTAS_LC           0
TX_RESPOSTAS_MT           0
TX_GABARITO_CN            0
TX_GABARITO_CH            0
TX_GABARITO_LC            0
TX_GABARITO_MT            0
TP_STATUS_REDACAO         0
NU_NOTA_COMP1             0
NU_NOTA_COMP2             0
NU_NOTA_COMP3             0
NU_NOTA_COMP4             0
NU_NOTA_COMP5             0
NU_NOTA_REDACAO           0
Q001                      0
Q002                      0
Q003                      0
Q004                      0
Q006                      0
Q022                      0
Q024                      0
Q025                      0
dtype: int64

In [8]:
df_2021

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
3,3,3,2,2,1,0,23,2,1,1,...,160,780,B,B,B,B,B,B,B,B
4,2,3,2,2,1,0,23,2,1,1,...,180,780,D,E,F,D,C,E,B,B
33,3,1,2,2,1,0,29,2,1,1,...,100,700,C,C,A,A,B,C,B,B
45,4,3,2,2,1,0,32,1,1,1,...,120,640,H,E,B,B,C,C,A,B
51,3,3,2,2,1,0,32,2,1,1,...,140,680,E,F,D,D,D,D,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389797,2,2,2,2,1,0,31,2,2,1,...,40,440,D,E,A,B,B,C,A,B
3389800,2,1,2,2,1,0,31,4,1,1,...,180,860,D,D,C,C,F,D,B,B
3389801,3,1,2,3,1,0,26,4,1,1,...,0,0,F,G,E,E,H,B,B,B
3389817,2,1,2,3,1,0,42,4,1,1,...,120,760,E,G,D,D,I,E,B,B
3389820,2,2,2,2,1,0,23,2,1,1,...,0,0,H,H,A,A,B,B,A,B

In [9]:
df_2021['TP_STATUS_REDACAO'].value_counts()

TP_STATUS_REDACAO
1    573892
4      8238
6      5679
3      1979
8      1299
9       408
2       408
7       286
Name: count, dtype: Int64

In [10]:
df_2021 = df_2021[df_2021['TP_STATUS_REDACAO'] == 1]

In [11]:
df_2021

,TP_FAIXA_ETARIA,TP_COR_RACA,TP_ST_CONCLUSAO,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q006,Q022,Q024,Q025
3,3,3,2,2,1,0,23,2,1,1,...,160,780,B,B,B,B,B,B,B,B
4,2,3,2,2,1,0,23,2,1,1,...,180,780,D,E,F,D,C,E,B,B
33,3,1,2,2,1,0,29,2,1,1,...,100,700,C,C,A,A,B,C,B,B
45,4,3,2,2,1,0,32,1,1,1,...,120,640,H,E,B,B,C,C,A,B
51,3,3,2,2,1,0,32,2,1,1,...,140,680,E,F,D,D,D,D,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3389778,3,3,2,2,1,0,22,2,1,1,...,160,660,C,B,A,A,A,C,A,A
3389793,2,1,2,3,1,0,35,4,1,1,...,200,960,E,G,B,D,L,D,D,B
3389797,2,2,2,2,1,0,31,2,2,1,...,40,440,D,E,A,B,B,C,A,B
3389800,2,1,2,2,1,0,31,4,1,1,...,180,860,D,D,C,C,F,D,B,B
3389817,2,1,2,3,1,0,42,4,1,1,...,120,760,E,G,D,D,I,E,B,B

In [12]:
df_2021['IN_TREINEIRO'].value_counts()

IN_TREINEIRO
0    573892
Name: count, dtype: Int64

In [13]:
df_2021['TP_PRESENCA_CN'].value_counts()

TP_PRESENCA_CN
1    573892
Name: count, dtype: Int64

In [14]:
df_2021['TP_PRESENCA_CH'].value_counts()

TP_PRESENCA_CH
1    573892
Name: count, dtype: Int64

In [15]:
df_2021['TP_ST_CONCLUSAO'].value_counts()

TP_ST_CONCLUSAO
2    573892
Name: count, dtype: Int64

In [16]:
df_2021.to_parquet("dados2021_limpos")